version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: local-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME_KIRYONG}
      POSTGRES_PASSWORD: ${DB_PASSWORD_KIRYONG}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # ì—¬ê¸°ì„œ ì°¸ì¡°í•˜ëŠ” ë³¼ë¥¨ ì´ë¦„

volumes:
  postgres_data: {}  # ğŸ‘ˆ ë£¨íŠ¸ì— ë°˜ë“œì‹œ ì •ì˜
